name: Frontend Unit Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

env:
  LARAVEL_BYPASS_ENV_CHECK: 1

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changed: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - './resources/assets/**'
              - './vite.config.js'
              - './package.json'
              - './yarn.lock'
              - './.eslintrc'
              - './cypress.json'

  test:
    needs: changes
    if: ${{needs.changes.outputs.changed == 'frontend'}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 14, 16, 17, 18 ] # 15 conflicts with @typescript-eslint/eslint-plugin@5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Run unit tests
        run: yarn test:unit
      - name: Collect coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  skip:
    needs: changes
    if: ${{needs.changes.outputs.changed != 'frontend'}}
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo "No frontend-related changes detected, skipping."
